#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
import textwrap
from pathlib import Path

import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import build_causal_package as base

ROOT = SCRIPT_DIR.parent
DERIVED_DIR = ROOT / "data" / "derived"
APPENDIX_PATH = ROOT / "appendix_tables.tex"
NUMBERS_PATH = DERIVED_DIR / "numbers.tex"


def format_num(value: float, digits: int = 3) -> str:
    return base.format_number(float(value), digits)


def write_numbers_tex(paper_df: pd.DataFrame, match_results: dict[str, object]) -> None:
    sentiment_by_accept = paper_df.groupby("accept")["mean_sentiment"].mean()
    score_by_accept = paper_df.groupby("accept")["mean_score"].mean()
    effects = match_results["effects"].set_index("specification")

    commands = {
        "TotalPapers": f"{len(paper_df):,}",
        "TotalReviews": f"{int(paper_df['num_reviews'].sum()):,}",
        "AcceptedPapers": f"{int(paper_df['accept'].sum()):,}",
        "OverallAcceptancePct": format_num(100 * paper_df["accept"].mean(), 1),
        "SentimentAcceptMean": format_num(sentiment_by_accept.loc[1], 3),
        "SentimentRejectMean": format_num(sentiment_by_accept.loc[0], 3),
        "MeanScoreAccept": format_num(score_by_accept.loc[1], 2),
        "MeanScoreReject": format_num(score_by_accept.loc[0], 2),
        "BorderlinePapers": f"{len(match_results['borderline_sample']):,}",
        "MatchedPairs": f"{int(match_results['primary_diag']['n_matched_pairs']):,}",
        "PSMATT": format_num(match_results["primary_diag"]["att"], 3),
        "PSMATTCI": f"[{format_num(match_results['primary_diag']['ci_low'], 3)}, {format_num(match_results['primary_diag']['ci_high'], 3)}]",
        "PSMNarrowATT": format_num(match_results["narrow_diag"]["att"], 3),
        "PSMNarrowCI": f"[{format_num(match_results['narrow_diag']['ci_low'], 3)}, {format_num(match_results['narrow_diag']['ci_high'], 3)}]",
        "PSMWideATT": format_num(match_results["wide_diag"]["att"], 3),
        "PSMWideCI": f"[{format_num(match_results['wide_diag']['ci_low'], 3)}, {format_num(match_results['wide_diag']['ci_high'], 3)}]",
        "PSMTercileATT": format_num(match_results["robust_diag"]["att"], 3),
        "PSMTercileCI": f"[{format_num(match_results['robust_diag']['ci_low'], 3)}, {format_num(match_results['robust_diag']['ci_high'], 3)}]",
        "BalanceStatus": "passed" if match_results["primary_diag"]["balance_pass"] else "flagged",
        "ClusterCount": f"{paper_df['topic_cluster'].nunique()}",
    }
    lines = ["% Auto-generated by scripts/build_psm_package.py"]
    for key, value in commands.items():
        lines.append(f"\\newcommand{{\\{key}}}{{{value}}}")
    NUMBERS_PATH.write_text("\n".join(lines) + "\n")


def write_appendix_tables(
    paper_df: pd.DataFrame,
    review_df: pd.DataFrame,
    topic_df: pd.DataFrame,
    audit_df: pd.DataFrame,
    match_results: dict[str, object],
) -> None:
    year_table = audit_df.groupby("year", as_index=False).agg(
        papers=("forum", "nunique"),
        parsed_reviews=("parsed_reviews", "sum"),
        decision_coverage=("has_decision", "sum"),
    )
    year_table["accept_rate"] = paper_df.groupby("year")["accept"].mean().values
    year_table["rating_parse_rate"] = review_df.groupby("year")["rating_parse_success"].mean().values
    year_table["confidence_parse_rate"] = review_df.groupby("year")["confidence_parse_success"].mean().values
    year_table["decision_parse_rate"] = paper_df.groupby("year")["decision_parse_success"].mean().values
    year_table["year"] = year_table["year"].astype(int)
    year_table["papers"] = year_table["papers"].astype(int)
    year_table["parsed_reviews"] = year_table["parsed_reviews"].astype(int)
    year_table["decision_coverage"] = year_table["decision_coverage"].astype(int)

    field_map = pd.DataFrame(
        {
            "year": [2018, 2019, 2020, 2021, 2022, 2023],
            "score_source": ["rating", "rating", "rating", "rating", "recommendation", "recommendation"],
            "text_source": [
                "review",
                "review",
                "review",
                "review",
                "summary_of_the_paper + summary_of_the_review",
                "summary_of_the_paper + strength_and_weaknesses + summary_of_the_review",
            ],
        }
    )

    effects = match_results["effects"].copy()
    effects["balance_pass"] = effects["balance_pass"].map(lambda value: "Pass" if bool(value) else "Flag")
    effects["matched_pairs"] = effects["matched_pairs"].astype(int)
    primary_balance = match_results["primary_balance"].copy()
    primary_counts = match_results["primary_counts"].copy()
    if not primary_counts.empty:
        primary_counts["year"] = primary_counts["year"].astype(int)
        primary_counts["matched_pairs"] = primary_counts["matched_pairs"].astype(int)
    else:
        primary_counts = pd.DataFrame({"year": [2018, 2019, 2020, 2021, 2022, 2023], "matched_pairs": [0] * 6})

    topic_short = topic_df.copy()
    topic_short["topic_cluster"] = topic_short["topic_cluster"].astype(int)
    topic_short["n_papers"] = topic_short["n_papers"].astype(int)
    topic_short["top_terms"] = topic_short["top_terms"].map(lambda s: textwrap.shorten(str(s), width=44, placeholder="..."))

    sections = [
        "\\clearpage",
        "\\onecolumn",
        "\\appendix",
        "\\renewcommand{\\thetable}{A\\arabic{table}}",
        "\\setcounter{table}{0}",
        "\\section*{Appendix: Report Tables}",
        "The appendix collects the raw-archive parsing diagnostics and the report-style matching tables used in the PSM-only version of the study.",
        "",
        base.latex_table_from_df(
            year_table,
            [
                "year",
                "papers",
                "parsed_reviews",
                "decision_coverage",
                "accept_rate",
                "rating_parse_rate",
                "confidence_parse_rate",
                "decision_parse_rate",
            ],
            "Raw-archive parsing diagnostics by year. The builder retains raw strings, parsed numeric fields, and parse-success flags for ratings, confidence, and final decisions.",
            "tab:app:harmonization",
            align="rrrrrrrr",
            float_fmt={
                "accept_rate": 3,
                "rating_parse_rate": 3,
                "confidence_parse_rate": 3,
                "decision_parse_rate": 3,
            },
        ),
        base.latex_table_from_df(
            field_map,
            ["year", "score_source", "text_source"],
            "Year-specific score and review-text sources used in the harmonized raw-archive parser.",
            "tab:app:fieldmap",
            align="rll",
        ),
        base.latex_table_from_df(
            effects,
            ["specification", "att", "ci_low", "ci_high", "matched_pairs", "balance_pass"],
            "Matched observational estimates. The table reports the primary 35th-65th percentile window, two prespecified window sensitivities, and the top-versus-bottom sentiment-tercile treatment sensitivity.",
            "tab:app:matchingeffects",
            align="lrrrrr",
            float_fmt={"att": 3, "ci_low": 3, "ci_high": 3},
        ),
        base.latex_table_from_df(
            primary_balance,
            ["label", "smd_before", "smd_after"],
            "Standardized mean differences before and after matching for the primary borderline specification. The balance target is $|SMD| < 0.10$ after matching.",
            "tab:app:balance",
            align="lrr",
            float_fmt={"smd_before": 3, "smd_after": 3},
        ),
        base.latex_table_from_df(
            primary_counts,
            ["year", "matched_pairs"],
            "Matched-pair counts by year for the primary borderline specification.",
            "tab:app:matchedcounts",
            align="rr",
        ),
        base.latex_table_from_df(
            topic_short,
            ["topic_cluster", "n_papers", "top_terms"],
            "Keyword-based topic-cluster proxies used in the propensity-score specification.",
            "tab:app:topics",
            align="rrl",
        ),
        "",
    ]
    APPENDIX_PATH.write_text("\n".join(sections))


def write_outputs(
    review_df: pd.DataFrame,
    paper_df: pd.DataFrame,
    topic_df: pd.DataFrame,
    audit_df: pd.DataFrame,
    match_results: dict[str, object],
) -> None:
    review_df.to_csv(DERIVED_DIR / "review_level_canonical.csv", index=False)
    paper_df.to_csv(DERIVED_DIR / "paper_level_canonical.csv", index=False)
    topic_df.to_csv(DERIVED_DIR / "topic_cluster_summary.csv", index=False)
    audit_df.to_csv(DERIVED_DIR / "parsing_audit_by_forum.csv", index=False)

    match_results["borderline_sample"].to_csv(DERIVED_DIR / "borderline_sample.csv", index=False)
    match_results["primary_work"].to_csv(DERIVED_DIR / "psm_primary_analytic_sample.csv", index=False)
    match_results["primary_pairs"].to_csv(DERIVED_DIR / "psm_primary_matched_pairs.csv", index=False)
    match_results["primary_balance"].to_csv(DERIVED_DIR / "psm_primary_balance.csv", index=False)
    match_results["primary_counts"].to_csv(DERIVED_DIR / "psm_primary_counts_by_year.csv", index=False)
    match_results["narrow_work"].to_csv(DERIVED_DIR / "psm_window_40_60_analytic_sample.csv", index=False)
    match_results["narrow_pairs"].to_csv(DERIVED_DIR / "psm_window_40_60_matched_pairs.csv", index=False)
    match_results["narrow_balance"].to_csv(DERIVED_DIR / "psm_window_40_60_balance.csv", index=False)
    match_results["wide_work"].to_csv(DERIVED_DIR / "psm_window_30_70_analytic_sample.csv", index=False)
    match_results["wide_pairs"].to_csv(DERIVED_DIR / "psm_window_30_70_matched_pairs.csv", index=False)
    match_results["wide_balance"].to_csv(DERIVED_DIR / "psm_window_30_70_balance.csv", index=False)
    match_results["robust_work"].to_csv(DERIVED_DIR / "psm_robust_analytic_sample.csv", index=False)
    match_results["robust_pairs"].to_csv(DERIVED_DIR / "psm_robust_matched_pairs.csv", index=False)
    match_results["robust_balance"].to_csv(DERIVED_DIR / "psm_robust_balance.csv", index=False)
    match_results["effects"].to_csv(DERIVED_DIR / "psm_effects.csv", index=False)
    match_results["overlap"].to_csv(DERIVED_DIR / "psm_overlap_summary.csv", index=False)

    summary = {
        "total_papers": int(len(paper_df)),
        "total_reviews": int(len(review_df)),
        "accept_rate": float(paper_df["accept"].mean()),
        "borderline_papers": int(len(match_results["borderline_sample"])),
        "primary_att": float(match_results["primary_diag"]["att"]),
        "primary_ci_low": float(match_results["primary_diag"]["ci_low"]),
        "primary_ci_high": float(match_results["primary_diag"]["ci_high"]),
        "primary_matched_pairs": int(match_results["primary_diag"]["n_matched_pairs"]),
        "primary_balance_pass": bool(match_results["primary_diag"]["balance_pass"]),
    }
    (DERIVED_DIR / "summary_metrics.json").write_text(json.dumps(summary, indent=2))
    write_numbers_tex(paper_df, match_results)
    write_appendix_tables(paper_df, review_df, topic_df, audit_df, match_results)


def main() -> None:
    base.ensure_dirs()
    base.setup_style()
    review_df, paper_df, topic_df, audit_df = base.build_canonical_tables()
    match_results = base.fit_matching_layer(paper_df)
    write_outputs(review_df, paper_df, topic_df, audit_df, match_results)
    base.plot_figure1(paper_df, match_results["borderline_sample"])
    base.plot_figure3(match_results)


if __name__ == "__main__":
    main()
